### ISSUE TITLE
It's sometimes fail to detect planes and is not expected in the result of WWDC example

### ISSUE THREAD

**Issue by skypu3** [maxxfrazer/FocusEntity#2]
Hi,
Thanks you to re-implement the focus square on RealityKit
I tried the newest example "Placing Objects and Handling 3D Interaction" from WWDC code.
The focus square can perfectly detect plane to close and open the square ...
However, I tried to use the FocusEntity component, it's sometimes fail to detect plane and is not expected in the result of WWDC example.

I check both code, the only difference is:
WWDC example's raycasting is based on ARRaycastResult from iOS 13
And FocusEntity is based on ARHitTestResult from iOS 11
is this the reason ?

**Comment by maxxfrazer** [comment]
Hi @skypu3, I'm not exactly sure what's the issue?
Correct, FocusEntity uses ARHitTestResult, but I haven't noticed any issue using that myself so far.
If ARKit has not yet detected the plane then this will use other methods to estimate the location of the plane, these are all found in [ARKit-SmartHitTest](https://github.com/maxxfrazer/ARKit-SmartHitTest). It uses ARHitTestResult for backwards compatibility with iOS 11.

Are you suggesting a feature update to use ARRaycastResult instead or are you having problems getting this to run in your project? Because "Placing Objects and Handling 3D Interaction" uses SceneKit, so this package is incompatible. If you think `ARRaycastResult` would be a better execution you're more than welcome to fork this repo with those changes and submit a Pull Request, any contributions are welcome!

PS I've made a GitHub Issue template for this repo, please use it in the future to make it as clear as possible what the problem/request is.

**Comment by rzulkoski** [comment]
Hi @maxxfrazer, I too was confused to see that you weren't using the new Raycast API's. With RealityKit requiring iOS 13 or later, I don't think you gain anything by using ARHitTestResult. I would love to see this feature implemented with `ARRaycastResult` in the future.

**Comment by maxxfrazer** [comment]
That is because the library used for getting the position `SmartHitTest` is backwards compatible with iOS 11 so needs ARHitTestResult.
Do you know what would be gained by changing to use ARRaycastResult @rzulkoski?

As mentioned, please feel free to open a PR if you have scope. I may be missing some feature that ARRaycastResult offers that would justify a change?
