### ISSUE TITLE
FocusEntityDelegate Bug

### ISSUE THREAD

**Issue by samberutu** [maxxfrazer/FocusEntity#38]
**Describe the bug**
i'm trying to connect swiftui UIViewRepresentable with FocusEntityDelegate. however FocusEntityDelegate has two functions but never gets called. i am trying to see if it is called or not using the print() command. but it doesn't appear
how can i use FocusEntityDelegate in my project?
I'm using the latest version of this library

![image](https://user-images.githubusercontent.com/45347400/185052130-35ae25ff-ad78-42b1-a7e2-9c566f5d6a3d.png)
![image](https://user-images.githubusercontent.com/45347400/185052273-799724cf-9cce-482f-be02-4d8ec6e34e07.png)
![image](https://user-images.githubusercontent.com/45347400/185053015-50e2ba16-d734-44eb-be65-eefba4de48b6.png)

**Environment:**
 - iOS 15.2
 - iphone 12
 - macOS 12.1
 - Xcode 13.3.1

**Comment by maxxfrazer** [comment]
You need to assign the FocusEntity delegate. Are you doing so?
https://swiftpackageindex.com/maxxfrazer/focusentity/2.2.6/documentation/focusentity/focusentity/delegate

Otherwise look in the package where the toTrackingState is called, add a breakpoint to see if it's ever hit. At that breakpoint, check if the delegate has a value. The code snippet should look like:
`self.delegate?.toTrackingState()`
