### ISSUE TITLE
Transparent Image Background

### ISSUE THREAD

**Issue by marcos-vinicius-mafei** [maxxfrazer/FocusEntity#44]
**Describe the bug**
When using images with transparent backgrounds like in the Example, the background becomes black. 

**To Reproduce**
Create FocusEntity using image like in the Example.

**Expected behavior**
Actual Transparent Background.

**Screenshots**
![IMG_A1D05D316F94-1](https://github.com/maxxfrazer/FocusEntity/assets/89421029/9fa7d41e-66f6-40d4-a2b9-693374644e72)

**Environment:**
 - iOS 17.2.1
 - macOS 14.2.1
 - Xcode 15.2

**Comment by marcos-vinicius-mafei** [comment]
Hello, @maxxfrazer .
I created a PR with a possible solution here:
https://github.com/maxxfrazer/FocusEntity/pull/45

The only problem is that it's still possible to see the rectangle below, like glass.

**Comment by marcos-vinicius-mafei** [comment]
Never mind, I fixed!
https://github.com/maxxfrazer/FocusEntity/pull/46

**Comment by marcos-vinicius-mafei** [comment]
After the changes:
![IMG_04850EFB6CD3-1](https://github.com/maxxfrazer/FocusEntity/assets/89421029/49e00dc4-fa24-49a1-858c-3d63d59a4d9f)

**Comment by maxxfrazer** [comment]
Fixed by #46

**Comment by firattamur** [comment]
Describe the bug
When using images with transparent backgrounds like in the Example, the background becomes black.

To Reproduce
Create FocusEntity using image like in the Example.

Expected behavior
Actual Transparent Background.

Environment:

iOS 18.5
macOS 15.5
Xcode 16.4

Screenshots
![Image](https://github.com/user-attachments/assets/f91efd32-50c6-41ec-a40c-6ff56e384188)

![Image](https://github.com/user-attachments/assets/69366427-f1ee-4b81-b39e-54e5c6791e32)
